name: CI

on: [push]

jobs:
  dstu1-php56:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: 5.6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 5
          configuration: ./phpunit/dstu1.xml

  dstu1-php70:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.0
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 6
          configuration: ./phpunit/dstu1.xml

  dstu1-php71:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 7
          configuration: ./phpunit/dstu1.xml

  dstu1-php72:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 8
          configuration: ./phpunit/dstu1.xml

  dstu1-php73:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 9
          configuration: ./phpunit/dstu1.xml

  dstu1-php74:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 9
          configuration: ./phpunit/dstu1.xml

  dstu1-php80:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 9
          configuration: ./phpunit/dstu1.xml

  dstu1-php81:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 9
          configuration: ./phpunit/dstu1.xml

  dstu1-php82:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: libxml simplexml json zip
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - name: Print version
        run: php -v
      - name: Generate code
        run: ./bin/generate.sh --useExisting
      - uses: php-actions/phpunit@v3
        with:
          version: 9
          configuration: ./phpunit/dstu1.xml
